# Generated by Django 5.0.6 on 2024-07-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_learningApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
